### PR TITLE
Switch to caffeine

### PR DESCRIPTION
**Pull request by denis-yuen**
Working on https://ucsc-cgl.atlassian.net/browse/SEAB-598

Despite https://github.com/dropwizard/dropwizard/pull/2400 could not do a clean removal of Guava since it is still a hardcoded dependency of dropwizard-jackson https://github.com/dropwizard/dropwizard/issues/3652

### CODE REVIEW

**Review by garyluu — APPROVED** [review]

**Comment by garyluu** [comment]
weird, looks like the import order isn't enforced

**Review by coverbeck — APPROVED** [review]
CacheBuilder is also used in other files, do you need/want to update those too?

**Comment by garyluu** [comment]
> weird, looks like the import order isn't enforced

ahh, maybe the auto-import reformat is applied before the checkstyle kicks in

**Comment by denis-yuen** [comment]
> CacheBuilder

good call, I must have searched on the wrong string

**Comment by garyluu** [comment]
wait a min...if the auto-format thing runs before the checkstyle check then checkstyle will never complain. if  it's run after, then checkstyle will kill the build beforehand. what to do...

**Comment by denis-yuen** [comment]
> wait a min...if the auto-format thing runs before the checkstyle check then checkstyle will never complain. if it's run after, then checkstyle will kill the build beforehand. what to do...

could do the JPA check thing. 
run impsort before checkstyle, but have a early build step fail the build if impsort results in changes (before going into lengthy integration tests)

**Comment by denis-yuen** [comment]
https://ucsc-cgl.atlassian.net/browse/SEAB-3217

**Review by coverbeck — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Pull request merged**
