### PR TITLE
Rollback transaction on error

### PR DESCRIPTION
**Pull request by coverbeck**
#4434 has the details.

I tested this manually and it works.

I cannot think of an easy way to do automated testing for this, especially with the #4433 fix (that PR fixes the bug that reveals this problem). Open to ideas.

We would need an exception to be thrown after the workflow version has been created. Maybe some fancy stuff with mocks, but even that would be tricky because the integration tests are run client-side, and the error needs to come on the server.

### CODE REVIEW

**Review by garyluu — APPROVED** [review]

**Review by denis-yuen — COMMENTED** [review]
>  cannot think of an easy way to do automated testing for this 

Probably missing something. 

But as strawman, wouldn't you need something like https://github.com/dockstore/dockstore/blob/8b158006cda66c2f0c42d80f51445ee0cfeba66f/dockstore-integration-testing/src/test/java/io/dockstore/webservice/WebhookIT.java#L417 

But with a repo that uses invalid yaml, throwing DockstoreYamlException on line 342 . Then you would hit up the database to confirm that it added one more lambdaEvent but didn't add a workflow version, sourcefile, etc.

**Comment by coverbeck** [comment]
> But as strawman, wouldn't you need something like
> 
> https://github.com/dockstore/dockstore/blob/8b158006cda66c2f0c42d80f51445ee0cfeba66f/dockstore-integration-testing/src/test/java/io/dockstore/webservice/WebhookIT.java#L417
> 
> But with a repo that uses invalid yaml, throwing DockstoreYamlException on line 342 . Then you would hit up the database to confirm that it added one more lambdaEvent but didn't add a workflow version, sourcefile, etc.

If it fails early, e.g., with an invalid yaml, it will throw the exception before it's created the workflow version, sourcefile, etc., so this fix will not come into play (i.e., there will be nothing to rollback). I need an error to occur server-side after the workflow version, etc. have been created.

There is a test for an [invalid dockstore.yml](https://github.com/dockstore/dockstore/blob/8b158006cda66c2f0c42d80f51445ee0cfeba66f/dockstore-integration-testing/src/test/java/io/dockstore/webservice/WebhookIT.java#L593); I can update that test to check those files haven't been created, but I suspect that's already the case.

**Review by NatalieEO — APPROVED** [review]

**Comment by denis-yuen** [comment]
Fair, so you need a failure that occurs late and we do parsing much too early. 
I wonder if you can mess with the lambda sequence. 

Like for me, when I use a fresh DB, often I need to login several times to iterate the user sequence past the ids that are already in use. Each failure iterates the id that it tries to use. Maybe if you break the lambda sequence, you can cause the first call to `lambdaEventDAO.create` to fail and the second one to succeed.

**Comment by coverbeck** [comment]
@denis-yuen 

The only thing I've been able to figure out, which is terrible, is using a global variable to force an exception to be thrown:

Integration test:
```
        SourceCodeRepoInterface.SIMULATE_ERROR = true;

        try {
            client.handleGitHubRelease(workflowRepo, BasicIT.USER_2_USERNAME, "refs/tags/0.2", installationId);
            fail("should not get here");
        } catch (Exception ex) {
            assertEquals(1, getFoobar1Workflow(client).getWorkflowVersions().size());
        } finally {
            SourceCodeRepoInterface.SIMULATE_ERROR = false;
        }

```
and in SourceCoreRepoInterface:

```
    public void updateVersionMetadata(String filePath, Version<?> version, DescriptorLanguage type, String repositoryId) {
        if (SIMULATE_ERROR) {
            throw new CustomWebApplicationException("fake exception", 400);
        }

```

This actually works from a test perspective (test fails without my fix, works with it), but I don't think it's a very good practice.

I tried modifying the database (dropping tables, columns, etc.), but the problem is that causes the failures too early, before there's anything to rollback. I think we basically need an exception coming from the Java code.

Thoughts?

**Comment by denis-yuen** [comment]
thoughts on the sequence thing? we've had to increment sequences before to avoid issues like with https://github.com/dockstore/dockstore/blob/d34af609a98da26d6af2fdf57ae6f6d4362a96df/dockstore-integration-testing/src/test/java/io/dockstore/webservice/UserResourceServicesIT.java#L111

I suspect that if you do something like `alter sequence lambdaevent_id_seq increment by -1` you can mess up the first invocation of the lambda with a conflict and then second time it would work.

**Comment by coverbeck** [comment]
> thoughts on the sequence thing? we've had to increment sequences before to avoid issues like with
> 
> https://github.com/dockstore/dockstore/blob/d34af609a98da26d6af2fdf57ae6f6d4362a96df/dockstore-integration-testing/src/test/java/io/dockstore/webservice/UserResourceServicesIT.java#L111
> 
> I suspect that if you do something like `alter sequence lambdaevent_id_seq increment by -1` you can mess up the first invocation of the lambda with a conflict and then second time it would work.

OK, I see. I'm not sure it will work, but I'll give it a shot. I suspect that will cause an error when trying to save to the DB, when the resource method exits, due to the `@UnitofWork` annotation, which is after my code change.

**Comment by denis-yuen** [comment]
> OK, I see. I'm not sure it will work, but I'll give it a shot. I suspect that will cause an error when trying to save to the DB, when the resource method exits, due to the `@UnitofWork` annotation, which is after my code change.

The reason why I'm thinking modify the sequence is that I believe the ID unlike other changes needs to be acquired and iterated before the transactions finishes. This is due to the possibility there may be multiple transactions in flight at the same time and they shouldn't get the same IDs. 

e.g.

> JPA sets the primary key after we invoke the EntityManager.persist() method and before we commit the transaction.

https://www.baeldung.com/jpa-strategies-when-set-primary-key

**Comment by coverbeck** [comment]
I was not able to get a good test for this; details in PR conversation. I did add update a test to check the number of versions did not increase after a failure, but that that test was already passing before my change.

Unfortunately the error needs to occur in a fairly specific place, which I can't do without hacking it.

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
