### PR TITLE
Feature/remove swagger event resource

### PR DESCRIPTION
**Pull request by garyluu**
Remove swagger annotations since the UI only uses OpenAPI

Fix positions of some properties

### CODE REVIEW

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/MetadataResourceHelper.java  -33
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/HostedWorkflowResource.java  -72
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/BioWorkflowDAO.java  -50
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/BitBucketSourceCodeRepo.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/TransactionExceptionMapper.java  -91
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/EntryDAO.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/ServiceEntryDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AliasableResourceInterface.java  -53
- dockstore-webservice/src/main/java/io/dockstore/webservice/api/PublishRequest.java  -50
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsApiServiceImpl.java  -67
- dockstore-common/src/main/java/io/dockstore/common/EntryType.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java  -4
- dockstore-webservice/src/main/java/io/dockstore/webservice/SimpleAuthenticator.java  -61
- dockstore-common/src/main/java/io/dockstore/common/Utilities.java  -74
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/CollectionDAO.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AliasResource.java  -42
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/TokenResource.java  -8
- dockstore-webservice/src/main/java/io/dockstore/webservice/permissions/InMemoryPermissionsImpl.java  -8
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/TRSListener.java  -83
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/BioWorkflow.java  -69
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Checksum.java  -46
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/UserDAO.java  -29
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/LabelDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/ElasticListener.java  -60
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/TOSVersion.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/ToolMode.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/DescriptionSource.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java  -12
- dockstore-common/src/main/java/io/dockstore/common/LanguageHandlerHelper.java  -80
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/dag/ElementsDefinition.java  -100
- dockstore-webservice/src/main/java/io/swagger/api/ToolsApiV1.java  -13
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ToolTesterResource.java  -16
- dockstore-webservice/src/main/java/io/dockstore/webservice/permissions/Role.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/PersistenceExceptionMapper.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryStarredSerializer.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Workflow.java  -91
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/TokenTypeConverter.java  -77
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tag.java  -70
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ImageRegistryFactory.java  -47
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AuthenticatedResourceInterface.java  -46
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/NotificationResource.java  -16
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ServiceResource.java  -40
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/StateManagerMode.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/QuayImageRegistry.java  -77
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/SourceControlResourceInterface.java  -62
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/StateListenerInterface.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/FileFormatDAO.java  -85
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsExtendedApi.java  -22
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Image.java  -61
- dockstore-webservice/src/main/java/io/dockstore/webservice/DockstoreWebserviceApplication.java  -94
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceFile.java  -86
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/WorkflowDAO.java  -40
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/WorkflowVersionDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EventResource.java  -28
- dockstore-webservice/src/main/java/io/dockstore/webservice/SimpleAuthorizer.java  -20
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/TokenDAO.java  -52
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/HostedToolResource.java  -31
- dockstore-common/src/main/java/io/dockstore/common/NextflowUtilities.java  -73
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Service.java  -14
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/TagDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java  -7
- dockstore-common/src/main/java/io/dockstore/common/DescriptorLanguage.java  -84
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceControlConverter.java  -77
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/tooltester/ToolTesterLogType.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/MetadataResource.java  -9
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/OrganizationDAO.java  -8
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsExtendedApiService.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/NotificationDAO.java  -15
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitLabSourceCodeRepo.java  -77
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java  -58
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/NextflowHandler.java  -88
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/PublicStateManager.java  -85
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerFactory.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/AbstractDockstoreDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EntryResource.java  -70
- dockstore-webservice/src/main/java/io/dockstore/webservice/CustomWebApplicationException.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Validation.java  -59
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Label.java  -50
- dockstore-webservice/src/main/java/io/dockstore/webservice/doi/DOIGeneratorFactory.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/CWLHandler.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/ChecksumConverter.java  -55
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java  -2
- dockstore-webservice/src/main/java/io/dockstore/webservice/DockstoreWebserviceConfiguration.java  -84
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/WorkflowVersion.java  -68
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/TemplateHealthCheck.java  -42
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Event.java  -5
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/FileFormat.java  -83
- dockstore-webservice/src/main/java/io/dockstore/webservice/permissions/PermissionsFactory.java  -69
- dockstore-common/src/main/java/io/dockstore/common/Registry.java  -81
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitHubSourceCodeRepo.java  -58
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/DAGHelper.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java  -94
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/ServiceDAO.java  -40
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/SitemapListener.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/EventDAO.java  -7
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ElasticSearchHealthCheck.java  -25
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsImplCommon.java  -82
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/ToolDAO.java  -76
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Version.java  -91
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractHostedEntryResource.java  -74
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/VersionDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GoogleHelper.java  -18
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java  -45
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/TokenType.java  -93
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/SourceCodeRepoFactory.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/WorkflowResource.java  -67
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/RSSListener.java  -70
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/FileDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/URIHelper.java  -55
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Entry.java  -86
- dockstore-webservice/src/main/java/io/swagger/api/impl/MetadataApiServiceImpl.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Organization.java  -10
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/User.java  -58
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsApiExtendedServiceImpl.java  -12
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryLabelHelper.java  -91
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/SourceCodeRepoInterface.java  -84
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Collection.java  -7
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/CacheConfigManager.java  -25
- dockstore-webservice/src/main/java/io/swagger/api/MetadataApiV1.java  -66
- dockstore-webservice/src/main/java/io/swagger/api/ToolClassesApiV1.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsApiExtendedServiceFactory.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Alias.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryVersionHelper.java  -81
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/PrivacyPolicyVersion.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Token.java  -38
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ObsoleteUrlFactory.java  -54
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tool.java  -69
- dockstore-webservice/src/main/java/io/dockstore/webservice/CharsetResponseFilter.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java  -32
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/FileFormatHelper.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/VersionMetadata.java  -25
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/WorkflowMode.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AliasHelper.java  -82
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EventSearchType.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/WDLHandler.java  -84
- dockstore-common/src/main/java/io/dockstore/common/VersionTypeValidation.java  -60
- dockstore-common/src/main/java/io/dockstore/common/SourceControl.java  -100
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolClassesApiServiceImpl.java  -55
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ZipSourceFileHelper.java  -4
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Notification.java  -3
- dockstore-webservice/src/main/java/io/swagger/model/ExtendedFileWrapper.java  -33
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ResourceUtilities.java  -81
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=4818997&bid=16022519)

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity decreasing per file
==============================
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=4818997&bid=16022519)

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=4818997&bid=16022519)

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=4818997&bid=16022519)

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity decreasing per file
==============================
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java  -1
+ dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java  -1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=4818997&bid=16022519)

**Comment by garyluu** [comment]
https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tool.java#L324

blocks it

**Pull request closed without merging**
