### PR TITLE
Feature/2871/trs hidden versions

### PR DESCRIPTION
**Pull request by garyluu**
For dockstore/dockstore#2871

Hidden versions were hidden by the TRS endpoint even from the owner. This PR reveals it...for the relative paths TRS endpoint

### CODE REVIEW

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Coverage increased per file
===========================
+ dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsApiServiceImpl.java  1
         

Complexity increasing per file
==============================
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsImplCommon.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/dockstore/dockstore/pullRequest?prid=4508682&bid=15193963)

**Comment by garyluu** [comment]
> 1. Code looks good, but I'm not 100% convinced this is the right behavior. I thought TRS was the public view of published workflows, and it seems odd you can bypass that here. If we're going this route, then shouldn't we also return your non-published workflows. OTOH, Denis triaged the issue, and I believe we've talked expanding more auth to TRS, so I'll concede in advance.
> 2. I didn't plow through the code, but what happens if you try to fetch a hidden version directly?

1. Ya, it's definitely strange, but we decided to use the TRS for displaying files on the website. Currently, the owner cannot see their own files so we definitely need this change for now.

2. Haven't tried, didn't really see a use case for this in the UI yet.

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 2
- Added 2
           

Complexity decreasing per file
==============================
+ dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsImplCommon.java  -3
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/dockstore/dockstore/pullRequest?prid=4508682&bid=15193963)

**Comment by denis-yuen** [comment]
@coverbeck @garyluu 
FYI, the GA4GH review committee talked a bit about best practices for adding auth to TRS. 
I think some undocumented/extensions the way we're doing it is within the spirit of what we intended

**Pull request merged**
