### PR TITLE
log github release rate limits and only get tags/branches (#4055)

### PR DESCRIPTION
**Pull request by NatalieEO**
* log github release rate limits and timings, changes .getRefs() call to only get tags/branches. Generate JWT before each workflow
https://ucsc-cgl.atlassian.net/browse/SEAB-2510

ugh rate limiting

### CODE REVIEW

**Comment by coverbeck** [comment]
Is this a cherry-pick from the the hotfix?

**Comment by NatalieEO** [comment]
> Is this a cherry-pick from the the hotfix?

yes it is

**Review by denis-yuen — APPROVED** [review]
Pending build success and due to cherrypick

**Review by coverbeck — APPROVED** [review]
>    Is this a cherry-pick from the the hotfix?
> yes it is

Asked because then that means I essentially already reviewed it. :)

**Review by garyluu — APPROVED** [review]

**Pull request merged**
