### PR TITLE
Check Zenodo rate limits

### PR DESCRIPTION
**Pull request by coverbeck**
**Description**
During Zenodo DOI harvesting, checks Zenodo rate limit remaining and waits until the limit is reset.

Not wild about doing `Thread.sleep()` in handling a request, but I did add a safeguard.

The other option is to handle this client-side with a script, e.g., get a list of all published workflows, find the unique GitHub repos, and run the endpoint against 1 repo at a time. It was pushing the limit of my bash scripting skills, but I could still do that. Let me know your thoughts.

**Review Instructions**
1. After deployed, invoke the the updateDois endpoint: `curl -X 'POST' 'https://staging.dockstore.org/api/workflows/updateDois' -H 'accept: application/json' -d '' -H "Authorization: Bearer {admin or curator token}"`
2. Check the CloudWatch logs and make sure there are no `133 per 1 minute` messages

**Issue**
SEAB-6747

**Security and Privacy**

If there are any concerns that require extra attention from the security team, highlight them here and check the box when complete. 

- [x] Security and Privacy assessed

e.g. Does this change...
* Any user data we collect, or data location?
* Access control, authentication or authorization?
* Encryption features?

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Review by david4096 — APPROVED** [review]

**Comment by kathy-t** [comment]
Does the endpoint end up processing everything in one go with this change? Or do we eventually exit because the rate limit reset time is too long?

To my understanding, the endpoint:
1. Gets a list of published GitHub workflows
2. Invokes the Zenodo API to find DOIs for the GitHub repo
3. Updates the workflows with the DOIs

If we get rate limited and the endpoint exits, we might end up in the same situation the second time because the list of workflows in 1 remains the same and we're invoking the Zenodo API again for the same set of workflows.

If that's the case, I would prefer the other solution you suggested:

>The other option is to handle this client-side with a script, e.g., get a list of all published workflows, find the unique GitHub repos, and run the endpoint against 1 repo at a time.

**Comment by coverbeck** [comment]
Going to hold off on this and try a client solution for 1.16. After that, we may not need it.

**Comment by denis-yuen** [comment]
@coverbeck any thoughts on this this week?

**Comment by coverbeck** [comment]
@denis-yuen Created a client-side script, linked in deploy notes, closing this given concerns.

**Pull request closed without merging**
