### PR TITLE
SEAB-6173: Remove getPublishedContainerSchema endpoint

### PR DESCRIPTION
**Pull request by svonworl**
**Description**
This PR removes the `getPublishedContainerSchema` endpoint from the webservice, which failed on this request:

```
curl -X GET http://localhost:4200/api/containers/schema/514/published
```

The failed request threw a NPE at:

https://github.com/dockstore/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/JsonLdRetriever.java#L226

The reason was that tag.getReference() was null.  About 1/3 of our old-style tools have at least one Tag with a null reference and will cause this endpoint to fail.

Upon inspection, we found that the endpoint had not been accessed in production in the last three months and was not used in the UI or CLI.

So, we removed the endpoint, and the entirety of the `JsonLdRetriever` class, which the endpoint used exclusively.

**Review Instructions**
Confirm that the endpoint has been removed.

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6173

**Security and Privacy**

No concerns.

- [x] Security and Privacy assessed

e.g. Does this change...
* Any user data we collect, or data location?
* Access control, authentication or authorization?
* Encryption features?

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Comment by denis-yuen** [comment]
> So, we removed the endpoint, and the entirety of the `JsonLdRetriever` class, which the endpoint used exclusively.

Hmmm, this was part an effort to make Dockstore's search results more relevant. It probably didn't get maintained and fell by the wayside, but I think we may want to take another look in the future. 
(Dockstore's search results still leave much to be desired)

More context at https://github.com/dockstore/dockstore-ui2/pull/667

**Review by denis-yuen — COMMENTED** [review]
May want to continue work on Dockstore's search results at some point, maybe kill the endpoints but not the supporting code.

**Review by coverbeck — APPROVED** [review]
It looks like the endpoint being removed was done way back when, in March 2017 (before I started on Dockstore!), and was never used. We do have an implementation that generates the json+ld in the browser via TypeScript that's working (well, it's generating JSON+LD), and is recognized by  Google Rich Results Test, although it annoyingly still doesn't show up in their search results.

Because the logic/effort for figuring out the details of what's in the JSON+LD are already in the UI, IMO it's OK to remove entirely -- we can always restore from history if needed.

**Comment by denis-yuen** [comment]
> We do have an implementation that generates the json+ld in the browser via TypeScript that's working (well, it's generating JSON+LD), and is recognized by Google Rich Results Test, although it annoyingly still doesn't show up in their search results.

Ok, cool. I didn't remember that part being moved.

**Review by denis-yuen — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Pull request merged**
