### PR TITLE
hotfix version of s3 update

### PR DESCRIPTION
**Pull request by denis-yuen**
**Description**
IMDSv2 support still seems broken despite a previous library update. 
AWS JDK versions move fast so updating, also found a source that claims that the only reason we're accessing instance metadata is to get the region for the tooltester bucket which we already know, so hard coding is worth a try 

**Issue**
https://github.com/dockstore/dockstore/issues/4359
See https://github.com/dockstore/dockstore/pull/4575 for develop counterpart

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] Check the Snyk dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future

### CODE REVIEW

**Comment by denis-yuen** [comment]
SonarCloud just seems bugged

**Review by garyluu — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]
Nice find, but confused, I could have sworn it worked.

**Review by Richard-Hansen — APPROVED** [review]

**Comment by denis-yuen** [comment]
> Nice find, but confused, I could have sworn it worked.

Yeah, I find it weird too. But worth a try in develop first at least

**Comment by denis-yuen** [comment]
(block until https://github.com/dockstore/dockstore/pull/4575 is reviewed on dev)

**Pull request closed without merging**
