### PR TITLE
handle non-DockerHub URL cases using determineImageRepository()

### PR DESCRIPTION
**Pull request by GFJHogue**
Main issue: #3820

Current logic for making tool-links assumes all non-Quay entries were DockerHub entries:
https://github.com/dockstore/dockstore/blob/96424cf3dc0f7ca623efc17670613db659242b55/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java#L361

We already have code to recognize the registry of an entry string: https://github.com/dockstore/dockstore/blob/96424cf3dc0f7ca623efc17670613db659242b55/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java#L373

This PR prevents creation of incorrect DockerHub URLS for non-DockerHub entries.

I also assume that non-DockerHub/Quay `dockerEntry` strings are valid URLs (which is at least true for Seven Bridges). Any exceptions to this would require coding additional cases...

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]

**Review by denis-yuen — APPROVED** [review]

**Review by denis-yuen — COMMENTED** [review]
```
[ERROR] Failures: 

[ERROR] io.dockstore.client.cli.DAGWorkflowTestIT.testHintsExpressionTool(io.dockstore.client.cli.DAGWorkflowTestIT)

[ERROR]   Run 1: DAGWorkflowTestIT.testHintsExpressionTool:278 should have docker requirement for vcf_merge

[ERROR]   Run 2: DAGWorkflowTestIT.testHintsExpressionTool:278 should have docker requirement for vcf_merge

[INFO] 

[ERROR] io.dockstore.client.cli.ToolsWorkflowTestIT.testToolCWL1Syntax(io.dockstore.client.cli.ToolsWorkflowTestIT)

[ERROR]   Run 1: ToolsWorkflowTestIT.testToolCWL1Syntax:220 pass_filter should have docker link

[ERROR]   Run 2: ToolsWorkflowTestIT.testToolCWL1Syntax:220 pass_filter should have docker link

[INFO] 

[ERROR] io.dockstore.client.cli.ToolsWorkflowTestIT.testToolCWL1SyntaxCorrectLink(io.dockstore.client.cli.ToolsWorkflowTestIT)

[ERROR]   Run 1: ToolsWorkflowTestIT.testToolCWL1SyntaxCorrectLink:247 merge_vcfs should not have docker link

[ERROR]   Run 2: ToolsWorkflowTestIT.testToolCWL1SyntaxCorrectLink:247 merge_vcfs should not have docker link
```

tests seem broken

**Comment by GFJHogue** [comment]
@denis-yuen Will look into those

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Coverage decreased per file
===========================
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ImageRegistryFactory.java  -41
- dockstore-webservice/src/main/java/io/swagger/api/impl/MetadataApiServiceImpl.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResource.java  -19
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/StateManagerMode.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ObsoleteUrlFactory.java  -54
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/dockerhub/DockerHubImage.java  -24
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/QuayImageRegistry.java  -61
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/TokenTypeConverter.java  -77
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryLabelHelper.java  -91
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryStarredSerializer.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/CWLHandler.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ElasticSearchHealthCheck.java  -25
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/PersistenceExceptionMapper.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/WorkflowVersionDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/dockerhub/DockerHubTag.java  -15
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/LambdaEventResource.java  -47
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/FileDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/CacheConfigManager.java  -25
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitLabSourceCodeRepo.java  -72
- dockstore-webservice/src/main/java/io/dockstore/webservice/CustomWebApplicationException.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguagePluginHandler.java  -51
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/FileFormatHelper.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AliasHelper.java  -82
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AliasableResourceInterface.java  -53
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/User.java  -54
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/DescriptorTypeConverter.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/TransactionExceptionMapper.java  -91
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/SitemapListener.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/TemplateHealthCheck.java  -42
- dockstore-common/src/main/java/io/dockstore/common/DescriptorLanguageSubclass.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Version.java  -92
- dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java  -72
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/BioWorkflow.java  -69
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerInterface.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceControlConverter.java  -72
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/NextflowHandler.java  -88
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Entry.java  -85
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/dag/ElementsDefinition.java  -100
- dockstore-webservice/src/main/java/io/openapi/api/impl/ServiceInfoApiServiceImpl.java  -6
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Organization.java  -10
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/WorkflowDAO.java  -35
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/ElasticListener.java  -74
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitHubSourceCodeRepo.java  -47
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/NotificationResource.java  -16
- dockstore-webservice/src/main/java/io/swagger/api/MetadataApiV1.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/CharsetResponseFilter.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Collection.java  -9
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AuthenticatedResourceInterface.java  -46
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/RSSListener.java  -70
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/MetadataResource.java  -12
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tag.java  -68
- dockstore-webservice/src/main/java/io/dockstore/webservice/SimpleAuthorizer.java  -20
- dockstore-webservice/src/main/java/io/swagger/api/impl/ApiV2BetaVersionConverter.java  -77
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/ChecksumConverter.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Tool.java  -75
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsApiServiceImpl.java  -72
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/TokenDAO.java  -47
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/TokenResource.java  -8
- dockstore-webservice/src/main/java/io/dockstore/webservice/doi/DOIGeneratorFactory.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java  -34
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/StateListenerInterface.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/SourceCodeRepoFactory.java  -71
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/SourceCodeRepoInterface.java  -81
- dockstore-common/src/main/java/io/dockstore/common/LanguageHandlerHelper.java  -80
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/UserDAO.java  -26
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/BioWorkflowDAO.java  -60
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/HostedWorkflowResource.java  -70
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoTagResource.java  -7
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/AbstractDockstoreDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/EntryDAO.java  -82
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/ToolDAO.java  -74
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Validation.java  -59
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/WorkflowVersion.java  -75
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Notification.java  -3
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/WorkflowMode.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/TokenType.java  -93
- dockstore-webservice/src/main/java/io/swagger/api/ToolClassesApiV1.java  -66
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/FileFormatDAO.java  -85
- dockstore-common/src/main/java/io/dockstore/common/VersionTypeValidation.java  -60
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsExtendedApi.java  -22
- dockstore-webservice/src/main/java/io/dockstore/webservice/SimpleAuthenticator.java  -61
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/OrganizationDAO.java  -8
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/DAGHelper.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/UserResourceDockerRegistries.java  -15
- dockstore-webservice/src/main/java/io/dockstore/webservice/permissions/Role.java  -87
- dockstore-webservice/src/main/java/io/openapi/model/ExtendedFileWrapper.java  -41
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/ZipSourceFileHelper.java  -4
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractHostedEntryResource.java  -71
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolsImplCommon.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/statelisteners/TRSListener.java  -83
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/DescriptionSource.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/LanguageHandlerFactory.java  -85
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/TOSVersion.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/ServiceEntryDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ServiceResource.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/HostedToolResource.java  -30
- dockstore-webservice/src/main/java/io/dockstore/webservice/languages/WDLHandler.java  -86
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/tooltester/ToolTesterLogType.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EntryResource.java  -55
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/VersionDAO.java  -87
- dockstore-webservice/src/main/java/io/dockstore/webservice/DockstoreWebserviceConfiguration.java  -84
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/SourceFile.java  -82
- dockstore-webservice/src/main/java/io/dockstore/webservice/permissions/PermissionsFactory.java  -60
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Image.java  -67
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java  -2
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/SourceControlResourceInterface.java  -70
- dockstore-common/src/main/java/io/dockstore/common/NextflowUtilities.java  -73
- dockstore-common/src/main/java/io/dockstore/common/Utilities.java  -70
- dockstore-webservice/src/main/java/io/swagger/api/ToolsApiV1.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GitHubHelper.java  -6
- dockstore-webservice/src/main/java/io/openapi/api/impl/ToolClassesApiServiceImpl.java  -55
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AliasResource.java  -42
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsApiExtendedServiceFactory.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Service.java  -14
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/ServiceDAO.java  -40
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/MetadataResourceHelper.java  -33
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/LabelDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/WorkflowResource.java  -61
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/PublicStateManager.java  -85
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/BitBucketSourceCodeRepo.java  -80
- dockstore-common/src/main/java/io/dockstore/common/LanguagePluginManager.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Event.java  -4
- dockstore-webservice/src/main/java/io/swagger/model/ExtendedFileWrapper.java  -33
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/PrivacyPolicyVersion.java  -100
- dockstore-webservice/src/main/java/io/swagger/api/impl/ToolClassesApiServiceImpl.java  -5
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/VersionMetadata.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/EntryVersionHelper.java  -82
- dockstore-webservice/src/main/java/io/dockstore/webservice/api/PublishRequest.java  -50
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/CollectionDAO.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/dockerhub/Results.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsApiExtendedServiceImpl.java  -12
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/ParsedInformation.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/URIHelper.java  -55
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/LicenseInformation.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Label.java  -50
- dockstore-webservice/src/main/java/io/dockstore/webservice/DockstoreWebserviceApplication.java  -96
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/LambdaEventDAO.java  -5
- dockstore-common/src/main/java/io/dockstore/common/Registry.java  -83
- dockstore-common/src/main/java/io/dockstore/common/DescriptorLanguage.java  -80
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/FileFormat.java  -83
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/CollectionResource.java  -4
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GoogleHelper.java  -18
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ToolTesterResource.java  -16
- dockstore-webservice/src/main/java/io/dockstore/webservice/permissions/InMemoryPermissionsImpl.java  -8
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/EventDAO.java  -11
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EventResource.java  -13
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Alias.java  -100
- dockstore-common/src/main/java/io/dockstore/common/SourceControl.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/AbstractWorkflowResource.java  -35
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/LambdaEvent.java  -6
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Token.java  -38
- dockstore-common/src/main/java/io/dockstore/common/Repository.java  -56
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/TagDAO.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Checksum.java  -65
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/proposedGA4GH/ToolsExtendedApiService.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/Workflow.java  -94
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/database/MyWorkflows.java  -95
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/EventSearchType.java  -100
- dockstore-common/src/main/java/io/dockstore/common/EntryType.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java  -58
- dockstore-webservice/src/main/java/io/dockstore/webservice/core/ToolMode.java  -100
- dockstore-webservice/src/main/java/io/dockstore/webservice/jdbi/NotificationDAO.java  -15
- dockstore-webservice/src/main/java/io/dockstore/webservice/resources/ResourceUtilities.java  -66
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=6295166&bid=20477743)

**Review by denis-yuen — APPROVED** [review]
codacy probably having teething issues since I fixed it

**Review by wshands — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Review by Ldcabansay — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Review by david4096 — APPROVED** [review]

**Pull request merged**
