### PR TITLE
DOCK-2170: Fix tools and DAG generation problem

### PR DESCRIPTION
**Pull request by svonworl**
**Description**
This PR fixes some bugs in the CWL "tool list" and DAG generation code.

While testing the previous PR (https://github.com/dockstore/dockstore/pull/5063), Charles found a workflow for which the list of tools and DAG were generated incorrectly:
https://qa.dockstore.org/workflows/github.com/sevenbridges-openworkflows/Broad-Best-Practice-Data-pre-processing-CWL1.0-workflow-GATK-4.1.0.0/GATK_4_1_0_0_data_pre_processing_workflow:master?tab=info

The problem was that the workflow ID included slashes, which messed up the workflow step ID and dependency parsing algorithms.  This PR changes the algorithms to be more robust.

Yes, that one function takes a ridiculous number of arguments, and now, it's even ridiculous-er, because I added an argument. 
 Alas, there's not an obviously-better alternative, unless we rewrite large chunks of the code (which we might if we ever implement multi-level DAG generation).

**Review Instructions**
Clone the repo of the above-mentioned workflow, register the cloned workflow, and confirm that the resulting list of tools and DAG are equivalent to those referenced by the original link.

**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2170
#4906

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Comment by denis-yuen** [comment]
> Alas, there's not an obviously-better alternative, unless we rewrite large chunks of the code (which we might if we ever implement multi-level DAG generation).

Can  you link to this, I think I'd like to read up on this and wonder if its a reference to a previous ticket/discussion

**Review by denis-yuen — APPROVED** [review]

**Comment by svonworl** [comment]
> > Alas, there's not an obviously-better alternative, unless we rewrite large chunks of the code (which we might if we ever implement multi-level DAG generation).
> 
> Can you link to this, I think I'd like to read up on this and wonder if its a reference to a previous ticket/discussion

I would add a link, but I don't have one. :)  The "not an obviously-better alternative" part is my software-engineering opinion, the multi-level DAG is an idea for a DAG that renders the steps in the subworkflows (rather than represent each subworkflow as a single node, as we have historically).

**Comment by denis-yuen** [comment]
> multi-level DAG generation

was mainly curious what this meant, thanks!

**Review by coverbeck — APPROVED** [review]
It would be nice to have a test for this so it doesn't break in the future.

**Pull request merged**
