### PR TITLE
Update to deal with jetty warning

### PR DESCRIPTION
**Pull request by denis-yuen**
https://github.com/dockstore/dockstore/security/dependabot/bom-internal/pom.xml/org.eclipse.jetty:jetty-io/open

For now, holding back liquibase update for upcoming ticket.

### CODE REVIEW

**Comment by denis-yuen** [comment]
The hell ....
```
ERROR [2021-04-12 20:33:46,162] liquibase.changelog.ChangeSet: Change Set migrations.1.10.0.xml::notification_seq::dyuen failed.  Error: ERROR: column "id" of relation "notification" is an identity column [Failed SQL: (0) ALTER TABLE public.notification ALTER COLUMN  id SET DEFAULT nextval('public.notification_id_seq')]
liquibase.exception.MigrationFailedException: Migration failed for change set migrations.1.10.0.xml::notification_seq::dyuen:
     Reason: liquibase.exception.DatabaseException: ERROR: column "id" of relation "notification" is an identity column [Failed SQL: (0) ALTER TABLE public.notification ALTER COLUMN  id SET DEFAULT nextval('public.notification_id_seq')]
 ```

**Comment by coverbeck** [comment]
> The hell ....
> ```
> ERROR [2021-04-12 20:33:46,162] liquibase.changelog.ChangeSet: Change Set migrations.1.10.0.xml::notification_seq::dyuen failed.  Error: ERROR: column "id" of relation "notification" is an identity column [Failed SQL: (0) ALTER TABLE public.notification ALTER COLUMN  id SET DEFAULT nextval('public.notification_id_seq')]
> liquibase.exception.MigrationFailedException: Migration failed for change set migrations.1.10.0.xml::notification_seq::dyuen:
>      Reason: liquibase.exception.DatabaseException: ERROR: column "id" of relation "notification" is an identity column [Failed SQL: (0) ALTER TABLE public.notification ALTER COLUMN  id SET DEFAULT nextval('public.notification_id_seq')]
> ```

Rings bells for my migration PR. I don't understand why you're running into it.

**Comment by denis-yuen** [comment]
Maybe I'll wait for your PR to be merged, maybe 21 overrides something

**Comment by denis-yuen** [comment]
Keeping some links for tomorrow

**Comment by denis-yuen** [comment]
Ok, bit of a problem to discuss. 

In a nutshell, because postgres has added support for identity columns, liquibase has moved to create identity columns by default, even when running old changesets.  3.10.2 creates a mix of sequence and identity based tables (notifications for example is sequence, enduser becomes identity). 3.10.3 moves to identity across the board   This is a problem for us:

1) Our changesets now create a subtly different testing database than what we actually have in prod. If there is a difference in behaviour, our tests will not catch it. In fact, 3.10.3 causes one migration that relies on sequences to fail. 
2) To solve this we have a few options
a) Somehow fix the existing migrations that are now creating identity columns to create sequence columns as they used to. I haven't figured out how to do this in 3.10.3 and hacks that allow this in 3.10.2 could fail in the future and/or hold us back from updates
b) Do some subtle revisionism. Migrate all prod tables to identity and then use identity columns in our tests
c) ??

Other notes:
There might not actually be a performance improvement with identity https://github.com/jhipster/generator-jhipster/pull/12098#issuecomment-660518251
Other similar observations on this issue with past changelogs https://github.com/liquibase/liquibase/pull/874#issuecomment-605033798 https://github.com/liquibase/liquibase/pull/1010#issuecomment-734815278

**Review by coverbeck — APPROVED** [review]

**Review by garyluu — APPROVED** [review]

**Review by GFJHogue — APPROVED** [review]

**Pull request merged**
