### PR TITLE
DOCK-2058: Gracefully reject relative paths in .dockstore.yml

### PR DESCRIPTION
**Pull request by svonworl**
**Description**
This PR improves the github apps push-processing code to gracefully reject entries with relative primary descriptor or test file paths.

The reported bug was not related to multiple entries, as suggested in the ticket.  Instead, it was triggered during the push of a workflow with a secondary descriptor, when a relative secondary descriptor path was converted to an absolute path.  In the case that the primary descriptor path was relative, `unsafeConvertRelativePathToAbsolutePath` threw an NPE, because `path.getRoot()` returns `null` for a relative path.

This PR makes two changes:
1. Adds a new `@AbsolutePath` constraint annotation to `YamlWorkflow` to validate that the primary descriptor and test file paths are absolute.
2. Modifies `LanguageHandlerHelper.unsafeConvertRelativePathToAbsolutePath` to throw an `IllegalArgumentException` with a usable message when it is passed a relative parent path.  Change #*1* should make the forementioned case much less likely, but as a backup...

To reduce clutter, we should probably move our custom constraint annotation definitions to a subpackage, I recommend we do that later, in #4985.

**Issue**
https://ucsc-cgl.atlassian.net/browse/DOCK-2058
#4715

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future

### CODE REVIEW

**Comment by coverbeck** [comment]
> Adds a new @AbsolutePath constraint annotation to YamlWorkflow to validate that the primary descriptor and test file paths are absolute.

I haven't looked at the code yet, but this prompts a question: are there any existing .dockstore.yml files for "successful" versions that don't have absolute paths for the primary descriptor or the test files?

If no, then we should be good; if yes, does, does the next push of a version might fail?

**Review by denis-yuen — APPROVED** [review]

**Comment by svonworl** [comment]
> > Adds a new @absolutepath constraint annotation to YamlWorkflow to validate that the primary descriptor and test file paths are absolute.
> 
> I haven't looked at the code yet, but this prompts a question: are there any existing .dockstore.yml files for "successful" versions that don't have absolute paths for the primary descriptor or the test files?
> 
> If no, then we should be good; if yes, does, does the next push of a version might fail?

There probably is a `.dockstore.yml` on dockstore.org that has relative paths in it, and yes, after this PR, the associated workflows would not register until they were fixed.

**Comment by denis-yuen** [comment]
> There probably is a `.dockstore.yml` on dockstore.org that has relative paths in it, and yes, after this PR, the associated workflows would not update until it was fixed.

Is it possible to SQL query for an estimate as to how many?

**Review by coverbeck — COMMENTED** [review]
> There probably is a `.dockstore.yml` on dockstore.org that has relative paths in it, and yes, after this PR, the associated workflows would not update until it was fixed.

Hmm, based on this comment and still not yet looking at code, I'm not sure we should do this. It's going to (relatively) silently break users' workflows; users may not know it's stopped working until they happen to look.

Quantifying how many and which workflows this would break would help -- what if breaks updates to all the Broad's gatk workflows? OTOH, if it only breaks a random hello world workflow, then it's probably OK.

**Pull request closed without merging**
