### PR TITLE
Use offset indexing for sourcefile content and apply text_analyzer

### PR DESCRIPTION
**Pull request by kathy-t**
**Description**
This is a solution to the [bug](https://github.com/dockstore/dockstore-ui2/pull/1850#issuecomment-1767680905) Steve found in https://github.com/dockstore/dockstore-ui2/pull/1850. See my comment about the bug [here](https://github.com/dockstore/dockstore-ui2/pull/1850#issuecomment-1769297096). 

This PR is a solution that was not mentioned in my comment.

The failure in the response was because the sourcefile content exceeded the [index.highlight.max_analyzed_offset](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules.html#index-max-analyzed-offset) value of 1,000,000. It turns out that the `index.highlight.max_analyzed_offset` is only applicable when highlighting is requested on a text that was indexed without offsets or term vectors so the solution in this PR is to index the sourcefile content using offsets. You can read about it [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-options.html), but it apparently speeds up highlighting for the unified highlight, which we use in https://github.com/dockstore/dockstore-ui2/pull/1850.

You can also see in the error message that Steve found that indexing with offsets is suggested for large texts:
> The length of [workflowVersions.sourceFiles.content] field of [1111] doc of [workflows] index has exceeded [1000000] - maximum allowed to be analyzed for highlighting. This maximum can be set by changing the [index.highlight.max_analyzed_offset] index level setting. For large texts, indexing with offsets or term vectors is recommended!

I also noticed that the tool mapping used a `text_analyzer` on the sourcefile content so I added this analyzer to the other 2 mappings.

**Review Instructions**
See https://github.com/dockstore/dockstore-ui2/pull/1850

**Issue**
[SEAB-5912](https://ucsc-cgl.atlassian.net/browse/SEAB-5912)

**Security and Privacy**

If there are any concerns that require extra attention from the security team, highlight them here.

e.g. Does this change...
* Any user data we collect, or data location?
* Access control, authentication or authorization?
* Encryption features?

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead. 

[SEAB-5912]: https://ucsc-cgl.atlassian.net/browse/SEAB-5912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]
Nice find!

**Comment by svonworl** [comment]
w00t

**Comment by svonworl** [comment]
I wonder, would it be a good idea to enable offset indexing on the other potentially-long fields, like `description`?

**Review by svonworl — APPROVED** [review]

**Comment by kathy-t** [comment]
> I wonder, would it be a good idea to enable offset indexing on the other potentially-long fields, like `description`?

Looking at the length of text for the fields we highlight in the database, I think `description` would be the next most likely to hit this error. However, the longest entry description is about 81,000 which is quite a bit away from 1,000,000. Testing locally, it took me a bit of trial and error to get the description up to 1,000,00 by stuffing the descriptor description with a bunch of words so I think it's unlikely that this would happen.

I lean towards not doing this for now so that we can observe how the offset indexing plays out for source files.

**Pull request merged**
