### PR TITLE
Merge 1.8.6 hotfix take3

### PR DESCRIPTION
**Pull request by denis-yuen**
Merge conflicts were a bit rougher than normal, so I did it this way to have tests run
But also show the original commits properly

### CODE REVIEW

**Comment by denis-yuen** [comment]
@garyluu 
Note that 4e59275addd1ebad90ae9e6d524496fb8b888337 (merge from develop) is overwriting the change from MyWorkflow to Workflow in "Fix/keep old models" to BioWorkflow
Not sure whether that merge is correct

**Comment by denis-yuen** [comment]
oh c'mon

**Comment by garyluu** [comment]
> oh c'mon

3rd time's the charm

**Comment by denis-yuen** [comment]
Note to self: next time, just stick to `git hf hotfix finish`

**Pull request merged**
