### PR TITLE
take us up through expected auto RDS updates

### PR DESCRIPTION
**Pull request by denis-yuen**
this is newer than what aws rds is running (11.10) , companion to https://github.com/dockstore/dockstore/pull/4388

this maintains performance as seen with 11.8 and with JDBC 42.2.19 but this is with JDBC 42.2.23 

Note that "Auto minor version upgrade" is on and will automatically take us to 11.12 at some point anyway

https://github.com/pgjdbc/pgjdbc/issues/2180 explains the pain we ran into with JDBC 42.2.21 but doesn't explain the full problem with postgres 12/13

background benchmarking at https://app.slack.com/archives/CEGMXHBHT/p1628280502020200

### CODE REVIEW

**Comment by denis-yuen** [comment]
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 374.108 s - in io.dockstore.webservice.WebhookIT
[INFO] testGithubDirDockstoreYml(io.dockstore.webservice.WebhookIT)  Time elapsed: 26.433 s
[INFO] testTestParameterPaths(io.dockstore.webservice.WebhookIT)  Time elapsed: 24.764 s
[INFO] testDescriptorChange(io.dockstore.webservice.WebhookIT)  Time elapsed: 24.058 s
[INFO] testTools(io.dockstore.webservice.WebhookIT)  Time elapsed: 27.407 s
[INFO] testGitHubReleaseNoWorkflowOnDockstore(io.dockstore.webservice.WebhookIT)  Time elapsed: 31.867 s
[INFO] testWorkflowMigration(io.dockstore.webservice.WebhookIT)  Time elapsed: 35.897 s
[INFO] testGitHubReleaseNoWorkflowOnDockstoreNoUser(io.dockstore.webservice.WebhookIT)  Time elapsed: 21.589 s
[INFO] testDockstoreYmlFilters(io.dockstore.webservice.WebhookIT)  Time elapsed: 32.491 s
[INFO] testDockstoreYmlAuthors(io.dockstore.webservice.WebhookIT)  Time elapsed: 36.593 s
[INFO] testInvalidDockstoreYmlFiles(io.dockstore.webservice.WebhookIT)  Time elapsed: 26.647 s
[INFO] testManualRefreshWorkflowWithGitHubApp(io.dockstore.webservice.WebhookIT)  Time elapsed: 22.476 s
[INFO] testDockstoreYmlPublish(io.dockstore.webservice.WebhookIT)  Time elapsed: 24.993 s
[INFO] testDeleteDefaultWorkflowVersion(io.dockstore.webservice.WebhookIT)  Time elapsed: 25.156 s
[INFO] Running io.dockstore.webservice.ServiceIT
```
Weird, better than develop but worse than 1.11
I hope we're not dealing with two issues

**Comment by denis-yuen** [comment]
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 348.652 s - in io.dockstore.webservice.WebhookIT
[INFO] testGithubDirDockstoreYml(io.dockstore.webservice.WebhookIT)  Time elapsed: 24.94 s
[INFO] testTestParameterPaths(io.dockstore.webservice.WebhookIT)  Time elapsed: 22.25 s
[INFO] testDescriptorChange(io.dockstore.webservice.WebhookIT)  Time elapsed: 22.295 s
[INFO] testTools(io.dockstore.webservice.WebhookIT)  Time elapsed: 25.455 s
[INFO] testGitHubReleaseNoWorkflowOnDockstore(io.dockstore.webservice.WebhookIT)  Time elapsed: 30.863 s
[INFO] testWorkflowMigration(io.dockstore.webservice.WebhookIT)  Time elapsed: 33.477 s
[INFO] testGitHubReleaseNoWorkflowOnDockstoreNoUser(io.dockstore.webservice.WebhookIT)  Time elapsed: 20.31 s
[INFO] testDockstoreYmlFilters(io.dockstore.webservice.WebhookIT)  Time elapsed: 30.345 s
[INFO] testDockstoreYmlAuthors(io.dockstore.webservice.WebhookIT)  Time elapsed: 33.566 s
[INFO] testInvalidDockstoreYmlFiles(io.dockstore.webservice.WebhookIT)  Time elapsed: 24.948 s
[INFO] testManualRefreshWorkflowWithGitHubApp(io.dockstore.webservice.WebhookIT)  Time elapsed: 21.268 s
[INFO] testDockstoreYmlPublish(io.dockstore.webservice.WebhookIT)  Time elapsed: 23.207 s
[INFO] testDeleteDefaultWorkflowVersion(io.dockstore.webservice.WebhookIT)  Time elapsed: 23.734 s
```
11.10
sigh

**Comment by denis-yuen** [comment]
```
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 357.133 s - in io.dockstore.webservice.WebhookIT
[INFO] testGithubDirDockstoreYml(io.dockstore.webservice.WebhookIT)  Time elapsed: 25.532 s
[INFO] testTestParameterPaths(io.dockstore.webservice.WebhookIT)  Time elapsed: 22.917 s
[INFO] testDescriptorChange(io.dockstore.webservice.WebhookIT)  Time elapsed: 23.726 s
[INFO] testTools(io.dockstore.webservice.WebhookIT)  Time elapsed: 28.022 s
[INFO] testGitHubReleaseNoWorkflowOnDockstore(io.dockstore.webservice.WebhookIT)  Time elapsed: 32.592 s
[INFO] testWorkflowMigration(io.dockstore.webservice.WebhookIT)  Time elapsed: 34.383 s
[INFO] testGitHubReleaseNoWorkflowOnDockstoreNoUser(io.dockstore.webservice.WebhookIT)  Time elapsed: 20.936 s
[INFO] testDockstoreYmlFilters(io.dockstore.webservice.WebhookIT)  Time elapsed: 30.647 s
[INFO] testDockstoreYmlAuthors(io.dockstore.webservice.WebhookIT)  Time elapsed: 33.66 s
[INFO] testInvalidDockstoreYmlFiles(io.dockstore.webservice.WebhookIT)  Time elapsed: 24.127 s
[INFO] testManualRefreshWorkflowWithGitHubApp(io.dockstore.webservice.WebhookIT)  Time elapsed: 21.509 s
[INFO] testDockstoreYmlPublish(io.dockstore.webservice.WebhookIT)  Time elapsed: 23.188 s
[INFO] testDeleteDefaultWorkflowVersion(io.dockstore.webservice.WebhookIT)  Time elapsed: 23.752 s
[INFO] Running io.dockstore.webservice.ServiceIT
```
11.9

**Comment by denis-yuen** [comment]
think bitbucket is having issues (workflow-integration-tests)

**Review by coverbeck — APPROVED** [review]
We'll need to reset dev back to 11.x. PG probably doesn't allow that; we may need to just spin up a new instance of RDS.

**Comment by denis-yuen** [comment]
> We'll need to reset dev back to 11.x. PG probably doesn't allow that; we may need to just spin up a new instance of RDS.

Depends on whether we figure this out and are still stuck on postgres 11 when dockstore 1.12 comes out. 

One known unknown, is the testing slowdown actually seen in real life on AWS RDS or is https://ucsc-cgl.atlassian.net/browse/DOCK-1854 just due to the jdbc driver problem?

**Comment by denis-yuen** [comment]
> We'll need to reset dev back to 11.x. PG probably doesn't allow that; we may need to just spin up a new instance of RDS.

Yeah, if we get to 1.12 and are still stuck at postgres 11. 
Hopefully, we figure this out by then. 

I guess the other unknown is whether the testing slowdown reflects a real slowdown on AWS.
Its possible that the JDBC slowdown was what you saw in

**Review by garyluu — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Comment by coverbeck** [comment]
> One known unknown, is the testing slowdown actually seen in real life on AWS RDS or is https://ucsc-cgl.atlassian.net/browse/DOCK-1854 just due to the jdbc driver problem?

#4347 was only seen locally. I think the verification of  #4338 shows there was no regression in prod.

I'll try #4347 again using these changes to see if it fixes it.

**Pull request merged**
