### PR TITLE
move out to github actions 

### PR DESCRIPTION
**Pull request by denis-yuen**
**Description**
Move docker upload into manually triggered workflow to re-use the upload artifact for actual docker build

Changes not obvious from PR
* New organization level secrets at https://github.com/organizations/dockstore/settings/secrets/actions
* tutorial for open ID connect is at https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
* configure-aws-credentials is a verified AWS action https://github.com/aws-actions/configure-aws-credentials

There is a new trust relationship in IAM on a role. Will want to look at `arn:aws:iam::<our account id>:role/OpenID_write_ui_builds_bucket`

Example successful run for reviewer to examine would be https://github.com/dockstore/dockstore/runs/6013166477?check_suite_focus=true

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-4188

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] Check the Snyk dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future

### CODE REVIEW

**Comment by denis-yuen** [comment]
circle ci build is kinda redundant to github actions anyway

**Review by coverbeck — APPROVED** [review]
Looks great, one less credential to rotate.

**Review by chmreid — APPROVED** [review]

**Review by david4096 — APPROVED** [review]
Looks good. I think it might not be worth it to add the IAM role via CloudFormation given it will always target one environment. Did you manually make the IAM changes already?

**Review by kathy-t — APPROVED** [review]

**Comment by denis-yuen** [comment]
> Looks good. I think it might not be worth it to add the IAM role via CloudFormation given it will always target one environment. Did you manually make the IAM changes already? 

Yeah, I created the role `OpenID_write_ui_builds_bucket`

**Pull request merged**
