### PR TITLE
bump regression tests to use 1.7

### PR DESCRIPTION
**Pull request by GFJHogue**
Main ticket: #3880

Regression tests are currently using `requirements.txt` for 1.6.0 which is too old, bumping to 1.7.0 (which also applies to 1.8 & 1.9).

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Comment by garyluu** [comment]
Hmm...kind of odd for me to approve/disapprove knowing that regression tests are still broken on the CI

**Comment by denis-yuen** [comment]
> Hmm...kind of odd for me to approve/disapprove knowing that regression tests are still broken on the CI
> 
> #3954

Haven't looked at code yet, but may need a fake branch to test this (assuming old behaviour of running on master and release branches carries over) 

https://github.com/dockstore/dockstore/blob/1.9.2/.travis.yml#L73

**Comment by garyluu** [comment]
> > Hmm...kind of odd for me to approve/disapprove knowing that regression tests are still broken on the CI
> > #3954
> 
> Haven't looked at code yet, but may need a fake branch to test this (assuming old behaviour of running on master and release branches carries over)
> 
> https://github.com/dockstore/dockstore/blob/1.9.2/.travis.yml#L73

Oh it's simple to test, just remove that line. Once it's finished and you know it passes, put it back.

**Review by denis-yuen — CHANGES_REQUESTED** [review]
Likely not running as per discussion

**Comment by GFJHogue** [comment]
Hit same errors as 1.10 ...

**Comment by GFJHogue** [comment]
Tested the erroring part of the regression integration tests locally with the same versions for everything and it works fine.
Likely an issue with the CI setup - opened a new ticket with more info: #3958

Anyhow, this PR shouldn't make a difference.

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
