### PR TITLE
testing sonarqube - failed, readme update

### PR DESCRIPTION
**Pull request by denis-yuen**

### CODE REVIEW

**Comment by denis-yuen** [comment]
SonarQube doesn't seem compatible with Java 
https://sonarcloud.io/documentation/analysis/automatic-analysis/

But the readme update might be useful anyway

**Review by garyluu — APPROVED** [review]
Weird because I use Sonarlint Intellij extension

**Comment by denis-yuen** [comment]
Maybe compiled languages cost too much to run on SonarCloud?

**Review by coverbeck — APPROVED** [review]

**Comment by coverbeck** [comment]
> Weird because I use Sonarlint Intellij extension

Double-weird because it says they support Scala and Kotlin, which target the Java VM.

**Pull request merged**
