### PR TITLE
Don't require openssl 1.1 for decrypt/encrypt

### PR DESCRIPTION
**Pull request by coverbeck**
With this, I can encrypt/descrypt with both openssl 1.1 and LibreSSL 2.6.5

Change discovered by @svonworl.

### CODE REVIEW

**Review by denis-yuen — APPROVED** [review]
works for me on ubuntu

**Review by garyluu — APPROVED** [review]

**Review by svonworl — APPROVED** [review]
Looks good to me!

**Comment by garyluu** [comment]
Just a note though. People should really not be using LibreSSL over OpenSSL in this day and age

**Review by NatalieEO — APPROVED** [review]

**Comment by coverbeck** [comment]
> Just a note though. People should really not be using LibreSSL over OpenSSL in this day and age

I had no idea. Looked into it briefly, and [this article](https://security.stackexchange.com/questions/112545/what-are-the-main-advantages-of-using-libressl-in-favor-of-openssl), which I know is not authoritative (and it's also old), states the opposite. Just curious, where do you see that?

**Comment by garyluu** [comment]
> > Just a note though. People should really not be using LibreSSL over OpenSSL in this day and age
> 
> I had no idea. Looked into it briefly, and [this article](https://security.stackexchange.com/questions/112545/what-are-the-main-advantages-of-using-libressl-in-favor-of-openssl), which I know is not authoritative (and it's also old), states the opposite. Just curious, where do you see that?

Ah, you're using outdated information. So the story is that OpenSSL had the heartbleed issue and rather than making a PR to OpenSSL to fix it, people decided to fork to LibreSSL. Some time later, OpenSSL fixed the heartbleed issue and implemented more a stringent security process that LibreSSL has not really kept up with. So in this day and age, LibreSSL is lacking in security and features.

As for source you can easily Google it and look at any modern posts

**Comment by coverbeck** [comment]
> As for source you can easily Google it and look at any modern posts. Here's a sample post https://lwn.net/Articles/841664/

That was the 3rd link in my Google search results; the first 2 extolled LibreSSL over OpenSSL. I guess I normally don't look past the first two results.

**Pull request merged**
