### PR TITLE
DOCK-2465: Try running extended CodeQL query suite

### PR DESCRIPTION
**Pull request by ll5zh**
**Description**
One of the goals of DOCK-2465 is to investigate why repos haven't produced many CodeQL warnings in the past 1-2 years (it seems that the latest warning is from [November 17 2022)](https://github.com/dockstore/dockstore/security/code-scanning?query=is%3Aopen+branch%3Adevelop+tool%3ACodeQL).

A speculation is that the default CodeQL query suite (currently being used) may not be comprehensive enough. In this PR, the dockstore build runs CodeQL's built-in `security-and-quality` queries, which are an extension of the default query suite. The additional queries are supposed to introduce greater coverage but often with lower severity and precision ([source](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs)).

**Review Instructions**
Take a look at what the new queries are scanning for, and evaluate whether they add value to the build/scan process. This is a link to the [CodeQL issues raised by the `security-and-quality` scan](https://github.com/dockstore/dockstore/security/code-scanning?page=1&query=is%3Aopen+tool%3ACodeQL+branch%3Adock-2465%2Fcodeql-queries+sort%3Acreated-desc).

The outputs under "Perform CodeQL analysis" in the workflow logs might store information about the scans (looks like the extended suite loaded 234 queries while the default scan loads 74):
- [Link to workflow log using `security-and-quality` scan](https://github.com/dockstore/dockstore/actions/runs/7747818033/job/21129123525)
- [Link to workflow log using default CodeQL scan](https://github.com/dockstore/dockstore/actions/runs/7661548296/job/20881150570)

**Issue**
[DOCK-2465](https://ucsc-cgl.atlassian.net/browse/DOCK-2465?atlOrigin=eyJpIjoiZDZiZWY0YjQ5NmU5NDViMzkwOWZlZDk3MmYzOTU4YmIiLCJwIjoiaiJ9)

**Security and Privacy**

If there are any concerns that require extra attention from the security team, highlight them here.

e.g. Does this change...
* Any user data we collect, or data location?
* Access control, authentication or authorization?
* Encryption features?

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead. 

[DOCK-2465]: https://ucsc-cgl.atlassian.net/browse/DOCK-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by denis-yuen** [comment]
Can also look at https://github.com/dockstore/dockstore/security/code-scanning?page=1&query=is%3Aopen+tool%3ACodeQL+branch%3Adock-2465%2Fcodeql-queries+sort%3Acreated-desc+severity%3Acritical%2Chigh to see what shows up (basically everything from 18 hours ago)

Nothing critical, but many many duplicate log injection warnings (which we were kinda of aware of already). 
I can kinda see why these aren't on by default but defer to @david4096 to see if this is worth turning on.

**Comment by coverbeck** [comment]
How did we discover the previous log injection issues? Was it going through code, or identified by a different tool? If it was a different tool, is there a mismatch? I know this tool is flagging log injections for code we have written specifically to prevent log injections, `Utilities.cleanForLogging()` (which the tool couldn't know, to be fair).

Just to make sure I understand, what are the options:

1. Rely on Snyk only for security static analysis (or is there already another one as well?)
2. Use both Snyk and CodeQL
3. Replace Snyk with CodeQL

If we don't think it would be too much noise, from what I understand, I'd vote for 2, but could be convinced 1 is enough.

**Comment by denis-yuen** [comment]
> How did we discover the previous log injection issues?

I think we knew this from SonarCloud, but it highlighted fewer occurrences 
https://github.com/dockstore/dockstore/security/code-scanning

**Comment by denis-yuen** [comment]
> Just to make sure I understand, what are the options:
> 
>     1. Rely on Snyk only for security static analysis (or is there already another one as well?)
> 
>     2. Use both Snyk and CodeQL
> 
>     3. Replace Snyk with CodeQL

I think Snyk is only doing vulnerable dependencies and not suspicious code. We turned off Snyk automatic PRs in favour of dependabot. 

CodeQL currently overlaps with SonarCloud which does look for vulnerabilities in the code like the logging issue. 

I think our options are more like:

1. Use CodeQL and SonarCloud as-is (knowing that CodeQL is very lax)
2. Tighten CodeQL (but get more noise) and SonarCloud as-is

**Comment by denis-yuen** [comment]
Related comment in https://github.com/dockstore/dockstore-cli/pull/277#issuecomment-1924447901

**Comment by denis-yuen** [comment]
recommending keeping the cli PR, but holding off on the webservice one (this one) since there is too much noise

**Review by denis-yuen — CHANGES_REQUESTED** [review]
(not really requesting changes, just highlighting comment above)

**Review by coverbeck — COMMENTED** [review]
> recommending keeping the cli PR, but holding off on the webservice one (this one) since there is too much noise

I'm good with that.

**Comment by denis-yuen** [comment]
As discussed, too much noise. Will revisit later

**Pull request closed without merging**
