### PR TITLE
Partial update to java 21

### PR DESCRIPTION
**Pull request by denis-yuen**
**Description**
Update to Java LTS 21, further pushing out our EOL.
For Java 17 Oracle EOL is Sept 2024, Eclipse Temurin has Oct 2027
For Java 21 Oracle EOL is Sept 2026, Eclipse Temurin has Sept 2029

Nonetheless, Java 21 is the next LTS version and should be better supported going forward. 
We are also hoping for performance improvements https://minborgsjavapot.blogspot.com/2023/01/java-21-performance-improvements.html

Note: we have to add in a check for bitbucket testing (not prod code), looks like gson has some slightly different behaviour in Java 21

On close, will create an issue to switch the bytecode compilation to Java 21 and the CircleCI image as well.
Without the new issue, most tests on CircleCI run on Java 21, but the regression, language parsing, and localstack tests run in Java 17. The Docker image should use Java 21 and the github actions tests should use 21

**Review Instructions**
Builds should continue to function, qa should work after nightly deploy

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6176
Follow-up with https://ucsc-cgl.atlassian.net/browse/SEAB-6269

**Security and Privacy**

Should be an improvement

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Comment by denis-yuen** [comment]
Mystery for tommorow, why on Earth do the BitBucket tests work locally but not on Circle?
Maybe the image?

**Comment by denis-yuen** [comment]
Well, the number of cache misses recorded in the circle ci job artifacts remains the same, so I guess we're good to go on that front

**Comment by denis-yuen** [comment]
Will keep bytecode target as Java 17 for now, looks like CircleCI image hasn't been updated on schedule yet https://discuss.circleci.com/t/linux-machine-executor-2024-q1-update/50198/2

**Comment by denis-yuen** [comment]
If you're on Linux, recommend something like the following to switch between Java 17 and 21 

```
$ cat ~/bin/switch_java_17.sh 
#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

sudo update-alternatives --set mvn /opt/apache-maven-3.9.2/bin/mvn
sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac

$ cat ~/bin/switch_java_21.sh 
#!/usr/bin/env bash
# Bash3 Boilerplate. Copyright (c) 2014, kvz.io

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# sudo update-alternatives --set mvn /opt/apache-maven-3.9.2/bin/mvn
sudo update-alternatives --set java /usr/lib/jvm/java-21-openjdk-amd64/bin/java
sudo update-alternatives --set javac /usr/lib/jvm/java-21-openjdk-amd64/bin/javac
```

**Review by coverbeck — APPROVED** [review]
Will there be another PR for

**Pull request merged**
