### PR TITLE
Relax line length style

### PR DESCRIPTION
**Pull request by garyluu**
Was considering whether to change the severity (basically no different than removing it) or relaxing the rule.

Decided to relax it

### CODE REVIEW

**Review by denis-yuen — APPROVED** [review]
Time to exercise that 4K monitor :wink:

**Review by coverbeck — APPROVED** [review]
That's pretty wide... Is the intent to bring it down in the future or keep it at 200?

**Comment by garyluu** [comment]
> That's pretty wide... Is the intent to bring it down in the future or keep it at 200?

Keep it at 200. The reason why I'm relaxing it is because codacy complains about everyone's PR when it's set to 140

**Comment by garyluu** [comment]
> Time to exercise that 4K monitor 😉

ya...resolution does nothing in this regard. I think I mentioned it in one of my presentations. a 4k phone at "normal" viewing distance can fit less readable characters than say a 1080p 23 inch monitor at "normal" viewing distance

**Review by wshands — APPROVED** [review]

**Pull request merged**
