### PR TITLE
SEAB-5111: added test for starring notebook

### PR DESCRIPTION
**Pull request by hyunnaye**
**Description**
This PR adds a test case verifying that the starring endpoint supports Notebooks.

**Review Instructions**
Verify that the new test checks that Notebooks can be starred/unstarred. 

**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5111

**Security**
If there are any concerns that require extra attention from the security team, highlight them here.

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Review by denis-yuen — APPROVED** [review]
minor change for readability

**Review by coverbeck — COMMENTED** [review]
I don't see any new tests, just improved importing. Did you accidentally revert something when you optimized the imports?

**Comment by denis-yuen** [comment]
> I don't see any new tests, just improved importing. Did you accidentally revert something when you optimized the imports?

Yeah, I think `50bc242987ed86bbc676ae33a8204824cd77b803` is wrong

**Comment by hyunnaye** [comment]
> I don't see any new tests, just improved importing. Did you accidentally revert something when you optimized the imports?

Yeah, not sure what happened there. Should be fixed now!

**Review by svonworl — APPROVED** [review]

**Review by coverbeck — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Pull request merged**
