### PR TITLE
multiple authors & ORCID authors in dockstore.yml

### PR DESCRIPTION
**Pull request by GFJHogue**
Main issue: https://ucsc-cgl.atlassian.net/browse/SEAB-2544
Previous draft PR: #4062

This PR adds an `authors` field in .dockstore.yml for workflows & services.
Authors with ORCID ids are handled as a ManyToMany relation on Version, separate from non-ORCID Authors (OneToMany).

### CODE REVIEW

**Comment by GFJHogue** [comment]
Adding integration test soon.
Opening to reviews early to hopefully get this PR this week.

**Comment by denis-yuen** [comment]
(I changed the base since the migration is to 1.11 and I think it makes sense to get the back-end changes in)

**Comment by denis-yuen** [comment]
Actually, I see some 1.12 stuff. Uh oh

**Comment by GFJHogue** [comment]
Closing this and remaking branch on 1.11

**Pull request closed without merging**
