### PR TITLE
Hook up filter for #2868

### PR DESCRIPTION
**Pull request by denis-yuen**
n/t

### CODE REVIEW

**Comment by denis-yuen** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- dockstore-webservice/src/main/java/io/openapi/api/impl/ToolsApiServiceImpl.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/dockstore/dockstore/pullRequest?prid=4995402&bid=16487259)

**Comment by garyluu** [comment]
Commit references issue but not PR, not sure if that's intentional

**Comment by denis-yuen** [comment]
> Commit references issue but not PR, not sure if that's intentional

Either/or *shrug*

**Comment by garyluu** [comment]
> > Commit references issue but not PR, not sure if that's intentional
> 
> Either/or _shrug_

Looks like it's less obvious that it's merged when looking at the issue

**Pull request merged**
