### PR TITLE
Hotfix/1.11.9

### PR DESCRIPTION
**Pull request by garyluu**
**Description**
Merge to master for staging release.

Had to manually add another commit for the generated poms since the current release process doesn't seem to handle it.

**Issue**
SEAB-3635

### CODE REVIEW

**Review by coverbeck — APPROVED** [review]

**Review by NatalieEO — APPROVED** [review]

**Comment by denis-yuen** [comment]
> Had to manually add another commit for the generated poms since the current release process doesn't seem to handle it. 

Yeah, this is a pain and I keep on forgetting

**Review by denis-yuen — COMMENTED** [review]
Think there are merge conflicts

**Comment by garyluu** [comment]
LGTM got stuck, added a minor commit to retrigger LGTM and see what happens

**Review by denis-yuen — APPROVED** [review]
If merge conflicts resolve

**Pull request merged**
