### PR TITLE
Don't return VersionMetadata.description in JSON response

### PR DESCRIPTION
**Pull request by coverbeck**
**Description**
It's already a property of Version; don't duplicate.

**Review Instructions**
* Follow instructions steps to reproduce in #5587, using qa instead of staging; the second curl command should not return a description.
* It would be good to do a sanity check in the UI to verify that nothing is broken by this change; view both public and unpublished workflows and tools in the UI.

**Issue**
#5587

**Security**
If there are any concerns that require extra attention from the security team, highlight them here.

Please make sure that you've checked the following before submitting your pull request. Thanks!

- [x] Check that you pass the basic style checks and unit tests by running `mvn clean install`
- [x] Ensure that the PR targets the correct branch. Check the milestone or fix version of the ticket.
- [x] Follow the existing JPA patterns for queries, using named parameters, to avoid SQL injection
- [x] If you are changing dependencies, check the Snyk status check or the dashboard to ensure you are not introducing new high/critical vulnerabilities
- [x] Assume that inputs to the API can be malicious, and sanitize and/or check for Denial of Service type values, e.g., massive sizes
- [x] Do not serve user-uploaded binary images through the Dockstore API
- [x] Ensure that endpoints that only allow privileged access enforce that with the `@RolesAllowed` annotation
- [x] Do not create cookies, although this may change in the future
- [x] If this PR is for a user-facing feature, create and link a documentation ticket for this feature (usually in the same milestone as the linked issue). Style points if you create a documentation PR directly and link that instead.

### CODE REVIEW

**Review by denis-yuen — APPROVED** [review]

**Comment by denis-yuen** [comment]
Assuming that cli doesn't use this (should be) and that UI doesn't (less clear, but assumed you then reviewer checked)

**Comment by svonworl** [comment]
Why is the description stored in `VersionMetadata` rather than `Version`?  Is the description is something that should be frozen when the version is snapshotted?

**Comment by coverbeck** [comment]
> Why is the description stored in `VersionMetadata` rather than `Version`? Is the description is something that should be frozen when the version is snapshotted?

Good question, answer unclear.

Description was added to both Version and VersionMetadata in #3024 without any clear comments I could find on why it was done that way.

I think it could make sense to update the description post-snapshotting, e.g., you want to clarify the instructions. Although the way we populate the field, it's only populated from other files from the repo, so it wouldn't be possible. Maybe it was to eventually allow manual editing of the description?

**Comment by svonworl** [comment]
> > Why is the description stored in `VersionMetadata` rather than `Version`? Is the description is something that should be frozen when the version is snapshotted?
> 
> Good question, answer unclear.
> 
> Description was added to both Version and VersionMetadata in #3024 without any clear comments I could find on why it was done that way.
> 
> I think it could make sense to update the description post-snapshotting, e.g., you want to clarify the instructions. Although the way we populate the field, it's only populated from other files from the repo, so it wouldn't be possible. Maybe it was to eventually allow manual editing of the description?

Makes sense, although I'm personally in the camp that the "snapshot" concept loses value if we allow components of a snapshotted entry to be later modified.  Stuff that's truly metadata, that's a different story...

In any case, this is a tangent issue that we can address later...

**Review by svonworl — APPROVED** [review]

**Review by kathy-t — APPROVED** [review]

**Comment by denis-yuen** [comment]
> I think it could make sense to update the description post-snapshotting, e.g., you want to clarify the instructions. Although the way we populate the field, it's only populated from other files from the repo, so it wouldn't be possible. Maybe it was to eventually allow manual editing of the description?

Guessing it may have been denormalization. i.e. rather than return the workflow and the default version, pre-calculate what needs to be shown, put it in the workflow and return just that

**Comment by coverbeck** [comment]
Closing this in favor of #5590

**Pull request closed without merging**
