### PR TITLE
Turn PGP back on

### PR DESCRIPTION
**Pull request by coverbeck**
https://ucsc-cgl.atlassian.net/browse/SEAB-2027

Passed twice on branch in CircleCI, if PR passes let's turn it back on in develop.

### CODE REVIEW

**Review by david4096 — APPROVED** [review]
Although I can approve this as is, I had expected this process to only be run when a release is performed and this seems like it is checking it for every build in CI? Perhaps this is because we don't have a separate script for when a tagged release is made.

https://ucsc-cgl.atlassian.net/browse/SEAB-1878

**Comment by coverbeck** [comment]
> Although I can approve this as is, I had expected this process to only be run when a release is performed and this seems like it is checking it for every build in CI? Perhaps this is because we don't have a separate script for when a tagged release is made.
> 
> https://ucsc-cgl.atlassian.net/browse/SEAB-1878

There had been some discussion about the initial fix in Slack which I should have captured in SEAB-1878-- the main concern then was that local builds were taking too long. So the fix was to turn it off locally and turn it on for CI, at least for the portion that builds the Docker image.

We are publishing every build to quay.io, and it seems like those images should all have been built from verified dependencies.

At that time, we were also building on Travis, which took much longer to complete, so the extra time spent building on CircleCI didn't matter -- it was still way less than the Travis time. Now that we're building only on CircleCI, hmm... We could only build if on a release branch or tag, but OTOH, if develop starts failing due to a PGP error, it would be good to have a heads up.

**Review by GFJHogue — APPROVED** [review]

**Comment by garyluu** [comment]
Hmm...I ran this locally and it worked. wonder when that package was fixed

**Review by garyluu — APPROVED** [review]

**Review by denis-yuen — COMMENTED** [review]
> At that time, we were also building on Travis, which took much longer to complete, so the extra time spent building on CircleCI didn't matter -- it was still way less than the Travis time. Now that we're building only on CircleCI, hmm... We could only build if on a release branch or tag, but OTOH, if develop starts failing due to a PGP error, it would be good to have a heads up.

Fair, how much of a performance hit is it?

**Comment by coverbeck** [comment]
> Fair, how much of a performance hit is it?

Very confusing, doesn't seem to make a difference. I wonder if the cache is carrying across or something. In the screenshot, develop should not be using pgp, yet it actually took a little longer than the PGP branch.

Screen Shot 2020-12-23 at 9 05 45 AM

**Review by denis-yuen — APPROVED** [review]

**Pull request merged**
