### PR TITLE
Feature/4121/ignore unknown properties

### PR DESCRIPTION
**Pull request by garyluu**
For #4121 

No longer fail on unknown properties.  Tests changed as a result

### CODE REVIEW

**Review by denis-yuen — APPROVED** [review]
On passing build (doesn't seem related, dammit PGP)
Disable PGP plugin on non-release branches for bonus points

**Review by coverbeck — APPROVED** [review]
It would be nice if there were warnings for misspelled properties, but I think it would take a major restructuring of the code to be able to do that..

For example, if I had the typo`filter` instead of the correct `filters` in my .dockstore.yml, it will now just silently not filter anything, and I wouldn't know unless I happened to notice versions popping up that aren't supposed to.

**Comment by denis-yuen** [comment]
> For example, if I had the typo`filter` instead of the correct `filters` in my .dockstore.yml, it will now just silently not filter anything, and I wouldn't know unless I happened to notice versions popping up that aren't supposed to.

It's a nice idea and worth a ticket. Might be able to use https://commons.apache.org/proper/commons-text/apidocs/org/apache/commons/text/similarity/LevenshteinDistance.html which should be on our classpath.

**Review by NatalieEO — APPROVED** [review]

**Comment by NatalieEO** [comment]
> It would be nice if there were warnings for misspelled properties, but I think it would take a major restructuring of the code to be able to do that..
> 
> For example, if I had the typo`filter` instead of the correct `filters` in my .dockstore.yml, it will now just silently not filter anything, and I wouldn't know unless I happened to notice versions popping up that aren't supposed to.

Maybe we could return a validation warning message like we do on descriptor files saying we didn't recognize x properties and ignored them.

**Comment by denis-yuen** [comment]
git's implementation https://stackoverflow.com/questions/9750653/did-you-mean-in-git

**Review by wshands — APPROVED** [review]

**Pull request merged**
